### ISSUE TITLE
connect callout-need service to filtering/sorting mechanisms

### ISSUE THREAD

**Issue by rainandwind0** [BoiseState/interfaith-donation#203] opened 2018-03-15 21:02 UTC
filtering/sorting mechanisms should trigger a change in what needs are being displayed.

**Comment by gbrasier** [comment] 2018-03-19 21:09
Closing this task because while #206 is a duplicate of this one, it has more information. I added the Acceptance Criteria of this task to #206.

**Closed as completed by gbrasier** 2018-03-19 21:09 UTC
Labels: front-end-ionic
